project_id = "xmhyjttyarskimsxcfhl"

[functions.subscribe-newsletter]
verify_jwt = false

[functions.publish-post]
verify_jwt = false

[functions.notify-subscribers]
verify_jwt = false

[functions.appointments-settings]
verify_jwt = false

[functions.appointments-availability]
verify_jwt = false

[functions.appointments-book]
verify_jwt = false

[functions.appointments-confirm]
verify_jwt = false

[functions.payments-initiate]
verify_jwt = false

[functions.payments-status]
verify_jwt = false

[functions.payments-paypal-capture]
verify_jwt = false

[functions.appointments-webhook-mpesa]
verify_jwt = false

[functions.appointments-webhook-airtel]
verify_jwt = false
